production:
 create_from_remote: no
 use.user.selected.activities: yes
 filing.number.prefix: FN101,FN102
 auto_set_appointment: true
 demographics.middle_name: false
 ask.multiple.phone.numbers: false
 demographics.ground_phone: false
 list.of.clinical.encounters.sequentially: weight and height,ttv vaccination,bp,anc visit type,obstetric history,medical history,surgical history,social history,lab results,anc examination,current pregnancy,manage appointments,give drugs,update outcome,hiv clinic registration,hiv staging,hiv reception,hiv clinic consultation,art adherence,manage art prescriptions
 statistics.show_encounter_types: REGISTRATION,ANC VISIT TYPE,VITALS,OBSERVATIONS,TREATMENT
 registration.clerk.roles: Registration,View Reports
 hsa.roles: Registration,Weight and Height,TTV Vaccination
 nurse.roles: Weight and Height,TTV Vaccination,BP,ANC Visit Type,Obstetric History,Medical History,Surgical History,Social History,Lab Results,ANC Examination,Current Pregnancy,Manage Appointments,Give Drugs,Update Outcome,HIV Clinic Registration,HIV Staging,HIV Reception,HIV Clinic Consultation,ART Adherence,Manage ART Prescriptions,ART Drug Dispensations,Registration,View Reports
 clinician.roles: Weight and Height,TTV Vaccination,BP,ANC Visit Type,Obstetric History,Medical History,Surgical History,Social History,Lab Results,ANC Examination,Current Pregnancy,Manage Appointments,Give Drugs,Update Outcome,HIV Clinic Registration,HIV Staging,HIV Reception,HIV Clinic Consultation,ART Adherence,Manage ART Prescriptions,ART Drug Dispensations,Registration,View Reports 

development:
 create_from_remote: no
 use.user.selected.activities: yes
 filing.number.prefix: FN101,FN102
 auto_set_appointment: true
 show.patient.confirmation: true
 demographics.middle_name: false
 ask.multiple.phone.numbers: false
 demographics.ground_phone: false
 list.of.clinical.encounters.sequentially: weight and height,ttv vaccination,bp,anc visit type,obstetric history,medical history,surgical history,social history,lab results,anc examination,current pregnancy,manage appointments,give drugs,update outcome,hiv clinic registration,hiv staging,hiv reception,hiv clinic consultation,art adherence,manage art prescriptions
 statistics.show_encounter_types: REGISTRATION,ANC VISIT TYPE,VITALS,OBSERVATIONS,TREATMENT
 registration.clerk.roles: Registration,Weight and Height,View Reports
 hsa.roles: Registration,Weight and Height,TTV Vaccination
 nurse.roles: Weight and Height,TTV Vaccination,BP,ANC Visit Type,Obstetric History,Medical History,Surgical History,Social History,Lab Results,ANC Examination,Current Pregnancy,Manage Appointments,Give Drugs,Update Outcome,HIV Clinic Registration,HIV Staging,HIV Reception,HIV Clinic Consultation,ART Adherence,Manage ART Prescriptions,ART Drug Dispensations,Registration,View Reports
 clinician.roles: Weight and Height,TTV Vaccination,BP,ANC Visit Type,Obstetric History,Medical History,Surgical History,Social History,Lab Results,ANC Examination,Current Pregnancy,Manage Appointments,Give Drugs,Update Outcome,HIV Clinic Registration,HIV Staging,HIV Reception,HIV Clinic Consultation,ART Adherence,Manage ART Prescriptions,ART Drug Dispensations,Registration,View Reports
   
test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
